//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS_SummerAssign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string VolApprovStat { get; set; }
        public string DriversLicense { get; set; }
        public string Centers { get; set; }
        public string Skills { get; set; }
        public string HomeAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Education { get; set; }
        public string Licenses { get; set; }
        public string EmergContactName { get; set; }
        public string EmergContactPhone { get; set; }
        public string EmergContactAddress { get; set; }
        public string SocialSecurity { get; set; }
        public string AvailabilityTimes { get; set; }
    }
}
